project:
  title: "bayesian-analysis-in-healthcare"
  execute-dir: project
  output-dir: _tmp

toc: true
toc-depth: 3
prefer-html: true

format:
  html:
    fig-align: center
    warning: false
    theme: lumen
    highlight-style: github
  gfm:
    fig-align: center
    warning: false

editor_options: 
  chunk_output_type: console