project:
  title: "bayesian-analysis-in-healthcare"
  execute-dir: project
  output-dir: _tmp
  post-render:
    - rsync -vau --remove-source-files _tmp/src/ output
    - find _tmp/ -type d -empty -delete

toc: true
toc-depth: 3
prefer-html: true

format:
  html:
    fig-width: 12
    fig-height: 8
    fig-align: center
    warning: false
    theme: lumen
    highlight-style: github
  gfm:
    fig-width: 12
    fig-height: 8
    fig-align: center
    warning: false

editor_options: 
  chunk_output_type: console