project:
  title: "bayesian-analysis-in-healthcare"
  execute-dir: project
  output-dir: _tmp

toc: true

format:
  gfm:
    fig-align: center
    warning: false

editor_options: 
  chunk_output_type: console