project:
  title: "bayesian-analysis-in-healthcare"
  execute-dir: project

toc: true
toc-depth: 3
prefer-html: true

format:
  gfm:
    fig-width: 12
    fig-height: 8
    fig-align: center
    warning: false
  html:
    fig-width: 12
    fig-height: 8
    fig-align: center
    warning: false
    theme: lumen
    highlight-style: github

editor_options: 
  chunk_output_type: console