name: 'Render Quarto Project'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto --version
    
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
        
      - name: Restore Project Dependencies from Lockfile
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
    
      - name: Install Linux System Dependencies
        run: |
          sudo apt-get install -y libglpk-dev
  
      - name: Render Quarto Files
        uses: quarto-dev/quarto-actions/render@v2

      - name: Commit Rendered Files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [-z "$(git status --porcelain)"]; then
              echo "::set-output name=push::false"
          else
              git commit -m "(GHA) Render Quarto files" -a
              echo "::set-output name=push::true"
          fi
          shell: bash

      - name: Push Changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
  
